version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: obraSocial_postgres
    restart: always
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Cd436146 
      POSTGRES_DB: obra_social
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
